# http://rainboard.laas.fr/project/roscontrol-sot/.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  CTEST_PARALLEL_LEVEL: 4

cache:
  paths:
    - ccache

.robotpkg-roscontrol-sot: &robotpkg-roscontrol-sot
  except:
    - gh-pages
  script:
    - mkdir -p ccache
    - cd /root/robotpkg/wip
    - git pull
    - cd roscontrol-sot
    - make checkout MASTER_REPOSITORY="git ${CI_PROJECT_DIR}/.git"
    - make install
    - cd $(make show-var VARNAME=WRKSRC)
    - make test

robotpkg-roscontrol-sot-16.04-release:
  <<: *robotpkg-roscontrol-sot
  image: eur0c.laas.fr:5000/stack-of-tasks/roscontrol-sot/roscontrol-sot:16.04

robotpkg-roscontrol-sot-16.04-debug:
  <<: *robotpkg-roscontrol-sot
  image: eur0c.laas.fr:5000/stack-of-tasks/roscontrol-sot/roscontrol-sot:16.04
  before_script:
    - echo PKG_OPTIONS.roscontrol-sot=debug >> /opt/openrobots/etc/robotpkg.conf

doc-coverage:
  <<: *robotpkg-roscontrol-sot
  image: eur0c.laas.fr:5000/stack-of-tasks/roscontrol-sot/roscontrol-sot:16.04
  before_script:
    - echo -e 'CXXFLAGS+= --coverage\nLDFLAGS+= --coverage\nPKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
  after_script:
    - cd /root/robotpkg/wip/roscontrol-sot
    - cd $(make show-var VARNAME=WRKSRC)
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}
    - mkdir -p ${CI_PROJECT_DIR}/coverage/
    - gcovr -r .
    - gcovr -r . --html --html-details -o ${CI_PROJECT_DIR}/coverage/index.html
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
      - coverage/

